AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/AccessModifierDeclarations:
  Exclude:
    - 'spec/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockChain:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Naming/MethodName:
  IgnoredPatterns:
    - '.*Type'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

Style/MutableConstant:
  Exclude:
    - 'spec/**/*'
